---

- hosts: deploytargets
  vars_files:
    - secrets.yml
  tasks:
    - name: update remote tag
      command: docker tag {{ appname }}:staging {{ appname }}:latest

    - name: restart app service
      systemd:
        state: restarted
        daemon_reload: yes
        name: "docker-{{ appname }}"

    - name: update local tag
      local_action: command docker tag {{ appname }}:staging {{ appname }}:latest
      run_once: true
