# Generated by Django 2.2.9 on 2020-05-30 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingesttoken", name="user",),
        migrations.AddField(
            model_name="ingesttoken",
            name="socialaccount",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="socialaccount.SocialAccount",
            ),
            preserve_default=False,
        ),
    ]
