# Generated by Django 2.2.9 on 2020-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200606_1547"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="name",
            field=models.CharField(default="test alert", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="alertstatus",
            name="state",
            field=models.CharField(
                choices=[("ALM", "ALARM"), ("OK", "OK")], default="OK", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="state",
            field=models.CharField(
                choices=[("ACT", "ACTIVE")], default="ACT", max_length=3
            ),
        ),
    ]
