# Generated by Django 2.2.9 on 2020-06-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200606_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertstatus",
            name="change_metric_row_sheet_index",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
