# Generated by Django 2.2.9 on 2020-06-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alertstatus_change_metric_row_sheet_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alertstatus",
            old_name="change_metric_row_sheet_index",
            new_name="change_sheet_row_start",
        ),
        migrations.AddField(
            model_name="alertstatus",
            name="change_sheet_row_end",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
