# Generated by Django 2.2.9 on 2020-06-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20200607_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="spreadsheet_id",
            field=models.TextField(default="backfilled"),
            preserve_default=False,
        ),
    ]
