# Generated by Django 2.2.9 on 2020-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20200611_2345"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertstatus",
            name="alarming_hosts",
            field=models.ManyToManyField(to="core.Host"),
        ),
    ]
