# Generated by Django 2.2.9 on 2020-06-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alertstatus_alarming_hosts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertstatus",
            name="alarming_hosts",
            field=models.ManyToManyField(blank=True, to="core.Host"),
        ),
    ]
