# Generated by Django 2.2.9 on 2020-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20200612_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertstatus",
            name="state",
            field=models.CharField(
                choices=[("ALM", "ALARM"), ("OK", "OK")], max_length=3
            ),
        ),
    ]
