# Generated by Django 2.2.9 on 2020-06-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20200612_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertAlarm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("change_metric_row_json", models.TextField()),
                ("change_sheet_row_start", models.PositiveIntegerField()),
                ("change_sheet_row_end", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="alert",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_host",
                to="core.Host",
            ),
        ),
        migrations.DeleteModel(name="AlertStatus",),
        migrations.AddField(
            model_name="alertalarm",
            name="alert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Alert"
            ),
        ),
        migrations.AddField(
            model_name="alertalarm",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_host",
                to="core.Host",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="alarms",
            field=models.ManyToManyField(through="core.AlertAlarm", to="core.Host"),
        ),
    ]
