# Generated by Django 2.2.9 on 2020-06-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20200613_1842"),
    ]

    operations = [
        migrations.RemoveField(model_name="alert", name="alarms",),
        migrations.AddField(
            model_name="alert",
            name="alarm_hosts",
            field=models.ManyToManyField(
                related_name="alarming_alert_set",
                through="core.AlertAlarm",
                to="core.Host",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="host",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.Host"
            ),
        ),
        migrations.AlterField(
            model_name="alertalarm",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Host"
            ),
        ),
    ]
