# Generated by Django 2.2.9 on 2020-07-17 00:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
        ("core", "0013_auto_20200613_1903"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSocialAccount",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("socialaccount.socialaccount",),
        ),
        migrations.AlterField(
            model_name="alert",
            name="host",
            field=models.ForeignKey(
                help_text="The host to monitor, or blank to apply to all hosts.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Host",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="name",
            field=models.CharField(
                help_text="A description of the alert.", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="ingesttoken",
            name="socialaccount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.EmailSocialAccount",
            ),
        ),
        migrations.AlterField(
            model_name="ingesttoken",
            name="value",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
