# Generated by Django 2.2.9 on 2020-08-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20200717_0027"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="alertalarm",
            constraint=models.UniqueConstraint(
                fields=("alert", "host"), name="unique_alert_by_host"
            ),
        ),
    ]
